
--CARGA COTIZACION
USE [010BDCOMUN]
SELECT B.item,B.codigo,ADESCRI,AUNIDAD,STSKDIS,
RSV_CANT,OF_CANT=SUM(A.OF_ARTCANT),NI_CANT=SUM(A.NI_CANT)
FROM  
	(select T.ITEM,T.codigo,ADESCRI,AUNIDAD,T.cantidad,STSKDIS,RSV_CANT=ISNULL(SUM(CANT_PEND),0.00) FROM  [010BDAPLICACION].DBO.carga_cotizacion T 
	INNER JOIN [010BDCOMUN].DBO.MAEART ON T.codigo=ACODIGO
	left join [010BDCOMUN].DBO.STKART on T.codigo=STCODIGO and STALMA='01'LEFT JOIN [022BDCOMUN].DBO.RESERVA_DET R ON T.codigo=R.CODIGO AND CANT_PEND>0
	GROUP BY T.item,T.codigo,ADESCRI,AUNIDAD,T.cantidad,STSKDIS) as B 

LEFT JOIN (SELECT CODIGOCENTROCOSTO,CODIGOOT,CC.CODIGO,OF_ARTCANT=ISNULL(O.OF_ARTCANT,0.00),NI_CANT=ISNULL(NI.NI_CANT,0.00)
			FROM [022BDCOMUN].DBO.CENCOSOT AS CC INNER JOIN [010BDCOMUN].DBO.ORD_FAB AS O ON CC.CODIGOOT=O.OF_COD AND OF_ESTADO ='ACTIVO'
			LEFT JOIN (SELECT c.CARFNDOC,NI_CANT= SUM(D.DECANTID) 
				FROM [010BDCOMUN].dbo.MOVALMCAB AS C INNER JOIN [010BDCOMUN].dbo.MOVALMDET AS D ON C.CANUMDOC=D.DENUMDOC 
				WHERE C.CAALMA=D.DEALMA AND C.CAALMA='01' AND C.CACODMOV IN ('IP','IE') AND C.CATD=D.DETD and c.CARFTDOC='OF' 
				group by C.CARFNDOC) AS NI ON CC.CODIGOOT=NI.CARFNDOC)AS A ON B.CODIGO=A.CODIGO
GROUP BY B.item,B.codigo,ADESCRI,AUNIDAD,B.cantidad,STSKDIS,RSV_CANT
order by B.item

--DETALLE POR ARTICULO
SELECT CODIGOCENTROCOSTO,CODIGOOT,CC.CODIGO,O.OF_ARTCANT,NI_CANT=ISNULL(NI.NI_CANT,0.00)
FROM [022BDCOMUN].DBO.CENCOSOT AS CC INNER JOIN [010BDCOMUN].DBO.ORD_FAB AS O ON CC.CODIGOOT=O.OF_COD AND OF_ESTADO ='ACTIVO'
LEFT JOIN (SELECT c.CARFNDOC,NI_CANT= SUM(D.DECANTID) 
	FROM [010BDCOMUN].dbo.MOVALMCAB AS C INNER JOIN [010BDCOMUN].dbo.MOVALMDET AS D ON C.CANUMDOC=D.DENUMDOC 
	WHERE C.CAALMA=D.DEALMA AND C.CAALMA='01' AND C.CACODMOV IN ('IP','IE') AND C.CATD=D.DETD and c.CARFTDOC='OF' 
	group by C.CARFNDOC) AS NI ON CC.CODIGOOT=NI.CARFNDOC
WHERE CC.CODIGO='140116161-003'

